### ISSUE TITLE
I got some errors. Can you help me?

### ISSUE THREAD

**Issue by alptolga** [joshuayabut/z-nomp#1]
xx@ubuntu:~/z-nomp$ npm start

> z-nomp@0.0.4 start /home/xx/z-nomp
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/ node init.js

2016-11-18 22:27:01 [POSIX]	[Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
undefined:1
yWEEc6m72SwgfusgoS9y":0.2,"t1Rfwn87KpYpiqMyWEEc6m72SwgfusgoS9y":0.2,},"payment
                                                                    ^
SyntaxError: Unexpected token }
    at Object.parse (native)
    at /home/xx/z-nomp/init.js:102:32
    at Array.forEach (native)
    at buildPoolConfigs (/home/xx/z-nomp/init.js:100:31)
    at init (/home/xx/z-nomp/init.js:431:19)
    at Object.<anonymous> (/home/xx/z-nomp/init.js:443:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.17
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! z-nomp@0.0.4 start: `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/ node init.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the z-nomp@0.0.4 start script 'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/ node init.js'.
npm ERR! This is most likely a problem with the z-nomp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/ node init.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs z-nomp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls z-nomp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xx/z-nomp/npm-debug.log

**Comment by joshuayabut** [comment]
This software isn't ready yet for mainnet use, but to solve the error you'll need to remove the comma  and the end of:

`"t1Rfwn87KpYpiqMyWEEc6m72SwgfusgoS9y":0.2,`

There's a bug with the transactions that doesn't reward the address correctly so don't use this on mainnet yet.

**Comment by alptolga** [comment]
Hi again, 
Thanks for your interest. I removed the comma and it began to works but it gave another error.
> z-nomp@0.0.4 start /home/xx/z-nomp
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/ node init.js

2016-11-19 02:23:37 [POSIX]	[Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2016-11-19 02:23:37 [Master]	[CLI] CLI listening on port 17117
2016-11-19 02:23:38 [Master]	[PoolSpawner] Spawned 1 pool(s) on 4 thread(s)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)
2016-11-19 02:23:38 [Master]	[Payment Processor] Payment processor died, spawning replacement...
2016-11-19 02:23:38 [Stats]	[Historics] Redis for stats had an error {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)
2016-11-19 02:23:38 [Master]	[Website] Website process died, spawning replacement...
2016-11-19 02:23:38 [Switching]	[Setup] (Thread 1) Loading last proxy state from redis
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)
2016-11-19 02:23:38 [Master]	[PoolSpawner] Fork 0 died, spawning replacement worker...
2016-11-19 02:23:39 [Switching]	[Setup] (Thread 2) Loading last proxy state from redis
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)
2016-11-19 02:23:39 [Master]	[PoolSpawner] Fork 1 died, spawning replacement worker...
2016-11-19 02:23:39 [Switching]	[Setup] (Thread 3) Loading last proxy state from redis
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)
2016-11-19 02:23:39 [Master]	[PoolSpawner] Fork 2 died, spawning replacement worker...
2016-11-19 02:23:39 [Switching]	[Setup] (Thread 4) Loading last proxy state from redis
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)
2016-11-19 02:23:39 [Master]	[PoolSpawner] Fork 3 died, spawning replacement worker...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)
2016-11-19 02:23:41 [Master]	[Payment Processor] Payment processor died, spawning replacement...
2016-11-19 02:23:41 [Stats]	[Historics] Redis for stats had an error {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)
2016-11-19 02:23:41 [Master]	[Website] Website process died, spawning replacement...
2016-11-19 02:23:41 [Switching]	[Setup] (Thread 1) Loading last proxy state from redis
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)
2016-11-19 02:23:41 [Master]	[PoolSpawner] Fork 0 died, spawning replacement worker...

**Comment by khoubaibc** [comment]
i think you have your Radis server is not started 
` Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED`
put this to run Radis in background 
`redis-server --daemonize yes`

**Comment by joshuayabut** [comment]
Also do a npm update and npm install to get the latest code. Good luck!
