### ISSUE TITLE
async: Callback was already called

### ISSUE THREAD

**Issue by zamerica** [joshuayabut/z-nomp#18]
When I start pool, I get this error. 

```
/home/zamerica/z-nomp/node_modules/async/dist/async.js:837
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /home/zamerica/z-nomp/node_modules/async/dist/async.js:837:32
    at /home/zamerica/z-nomp/node_modules/async/dist/async.js:3691:13
    at apply (/home/zamerica/z-nomp/node_modules/async/dist/async.js:21:25)
    at /home/zamerica/z-nomp/node_modules/async/dist/async.js:56:12
    at /home/zamerica/z-nomp/libs/paymentProcessor.js:93:17
    at itemFinished (/home/zamerica/z-nomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /home/zamerica/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/home/zamerica/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/zamerica/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at emitNone (events.js:91:20)
2016-11-30 17:16:20 [Master]    [Payment Processor] Payment processor died, spawning replacement...
```

I am using Arch Linux, node v7.2.0, npm 3.10.9.

**Comment by megacrypto** [comment]
same here on ubuntu 16.04 with same node & npm versions

**Comment by aayanl** [comment]
you need to run node v7, do `sudo n stable` to get it

**Comment by aayanl** [comment]
First try `sudo n stable`, if it doesn't work

https://github.com/zone117x/node-open-mining-portal/issues/470 try those dependency versions

**Comment by megacrypto** [comment]
tried to install nodejs 0.10 with the following command (on ubuntu 10.04)

 `curl -sL https://deb.nodesource.com/setup_0.10 | sudo -E bash -`

and ended up with v4.x because 0.10 is depreciated !!

so looking up some other ways, found this:

```
sudo npm cache clean -f
sudo npm install -g n
sudo n 0.10.48
```
and ended up with

```
node -v
v0.10.48
```

now, when i build the project using:

```
rm -r node_modules
npm update
```

everything starts up well then fails at equihashverify build:

```
npm WARN engine stratum-pool@0.1.6: wanted: {"node":">=7"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine equihashverify@0.0.1: wanted: {"node":">=0.12"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine bitcoinjs-lib-zcash@2.3.0: wanted: {"node":">=0.12"} (current: {"node":"0.10.48","npm":"2.15.1"})
```

and then this:

```
> equihashverify@0.0.1 install /home/mylin/ZNOMP/znomp/node_modules/stratum-pool/node_modules/equihashverify
> node-gyp rebuild

make: Entering directory '/home/mylin/ZNOMP/znomp/node_modules/stratum-pool/node_modules/equihashverify/build'
  CC(target) Release/obj.target/libequi/src/equi/equi.o
../src/equi/equi.c: In function ‘isZero’:
../src/equi/equi.c:78:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < len; i++) {
                     ^
  CC(target) Release/obj.target/libequi/src/equi/endian.o
  SOLINK(target) Release/obj.target/equi.so
  COPY Release/equi.so
  CXX(target) Release/obj.target/equihashverify/equihashverify.o
../equihashverify.cc:14:23: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a template type
 void Verify(const v8::FunctionCallbackInfo<Value>& args) {
                       ^
../equihashverify.cc:14:43: error: expected ‘,’ or ‘...’ before ‘<’ token
 void Verify(const v8::FunctionCallbackInfo<Value>& args) {
                                           ^
../equihashverify.cc: In function ‘void Verify(int)’:
../equihashverify.cc:16:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
   HandleScope scope(isolate);
                            ^
In file included from /home/mylin/.node-gyp/0.10.48/include/node/node.h:62:0,
                 from ../node_modules/nan/nan.h:47,
                 from ../equihashverify.cc:1:
/home/mylin/.node-gyp/0.10.48/include/node/v8.h:473:3: note: candidate: v8::HandleScope::HandleScope(const v8::HandleScope&)
   HandleScope(const HandleScope&);
   ^
/home/mylin/.node-gyp/0.10.48/include/node/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
/home/mylin/.node-gyp/0.10.48/include/node/v8.h:448:3: note: candidate: v8::HandleScope::HandleScope()
   HandleScope();
   ^
/home/mylin/.node-gyp/0.10.48/include/node/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
../equihashverify.cc:18:7: error: ‘args’ was not declared in this scope
   if (args.Length() < 2) {
       ^
../equihashverify.cc:19:12: error: ‘class v8::Isolate’ has no member named ‘ThrowException’
   isolate->ThrowException(Exception::TypeError(
            ^
../equihashverify.cc:20:5: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
     String::NewFromUtf8(isolate, "Wrong number of arguments")));
     ^
../equihashverify.cc:24:26: error: ‘args’ was not declared in this scope
   Local<Object> header = args[0]->ToObject();
                          ^
../equihashverify.cc:28:12: error: ‘class v8::Isolate’ has no member named ‘ThrowException’
   isolate->ThrowException(Exception::TypeError(
            ^
../equihashverify.cc:29:5: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
     String::NewFromUtf8(isolate, "Arguments should be buffer objects.")));
     ^
../equihashverify.cc: In function ‘void Init(v8::Handle<v8::Object>)’:
../equihashverify.cc:43:44: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [7], void (&)(int))’
   NODE_SET_METHOD(exports, "verify", Verify);
                                            ^
In file included from ../node_modules/nan/nan.h:47:0,
                 from ../equihashverify.cc:1:
/home/mylin/.node-gyp/0.10.48/include/node/node.h:112:6: note: candidate: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
 void SetMethod(target_t obj, const char* name,
      ^
/home/mylin/.node-gyp/0.10.48/include/node/node.h:112:6: note:   template argument deduction/substitution failed:
../equihashverify.cc:43:44: note:   cannot convert ‘Verify’ (type ‘void(int)’) to type ‘v8::InvocationCallback {aka v8::Handle<v8::Value> (*)(const v8::Arguments&)}’
   NODE_SET_METHOD(exports, "verify", Verify);
                                            ^
In file included from ../equihashverify.cc:8:0:
../src/equi/equi.h: At global scope:
../src/equi/equi.h:22:13: warning: ‘void digestInit(crypto_generichash_blake2b_state*, int, int)’ declared ‘static’ but never defined [-Wunused-function]
 static void digestInit(crypto_generichash_blake2b_state *S, const int n, const int k);
             ^
../src/equi/equi.h:24:13: warning: ‘void expandArray(const unsigned char*, size_t, unsigned char*, size_t, size_t, size_t)’ declared ‘static’ but never defined [-Wunused-function]
 static void expandArray(const unsigned char *in, const size_t in_len,
             ^
../src/equi/equi.h:28:12: warning: ‘int isZero(const uint8_t*, size_t)’ declared ‘static’ but never defined [-Wunused-function]
 static int isZero(const uint8_t *hash, size_t len);
            ^
../src/equi/equi.h:30:13: warning: ‘void generateHash(crypto_generichash_blake2b_state*, uint32_t, uint8_t*, size_t)’ declared ‘static’ but never defined [-Wunused-function]
 static void generateHash(crypto_generichash_blake2b_state *S, const uint32_t g, uint8_t *hash, const size_t hashLen);
             ^
equihashverify.target.mk:100: recipe for target 'Release/obj.target/equihashverify/equihashverify.o' failed
make: *** [Release/obj.target/equihashverify/equihashverify.o] Error 1
make: Leaving directory '/home/mylin/ZNOMP/znomp/node_modules/stratum-pool/node_modules/equihashverify/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.4.0-51-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mylin/ZNOMP/znomp/node_modules/stratum-pool/node_modules/equihashverify
gyp ERR! node -v v0.10.48
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! equihashverify@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the equihashverify@0.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the equihashverify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs equihashverify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls equihashverify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mylin/ZNOMP/znomp/npm-debug.log

```

from what i can read, it needs different versions of nodejs for these 3 modules:

```
npm WARN engine stratum-pool@0.1.6: wanted: {"node":">=7"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine equihashverify@0.0.1: wanted: {"node":">=0.12"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine bitcoinjs-lib-zcash@2.3.0: wanted: {"node":">=0.12"} (current: {"node":"0.10.48","npm":"2.15.1"})
```

**Comment by joshuayabut** [comment]
Should be fixed now. Please do a git pull and retry. Thanks! https://github.com/joshuayabut/z-nomp/pull/19

**Comment by megacrypto** [comment]
reverted back to nodejs 7.2 and did an update, but seems to be an error with equihashverify .... posted it on a new thread
