### ISSUE TITLE
Zcash is not supported yet

### ISSUE THREAD

**Issue by joshuayabut** [joshuayabut/z-nomp#39]
Adding this so it can be tracked...

In order to support the Zcash blockchain we need to generate a founder's reward transaction in discovered blocks.

**Comment by joshuayabut** [comment]
These are the relevant checks from the Zcash codebase.

/src/chainparams.cpp
```
// Block height must be >0 and <=last founders reward block height
// Index variable i ranges from 0 - (vFoundersRewardAddress.size()-1)
std::string CChainParams::GetFoundersRewardAddressAtHeight(int nHeight) const {
    int maxHeight = consensus.GetLastFoundersRewardBlockHeight();
    assert(nHeight > 0 && nHeight <= maxHeight);

    size_t addressChangeInterval = (maxHeight + vFoundersRewardAddress.size()) / vFoundersRewardAddress.size();
    size_t i = nHeight / addressChangeInterval;
    return vFoundersRewardAddress[i];
}

// Block height must be >0 and <=last founders reward block height
// The founders reward address is expected to be a multisig (P2SH) address
CScript CChainParams::GetFoundersRewardScriptAtHeight(int nHeight) const {
    assert(nHeight > 0 && nHeight <= consensus.GetLastFoundersRewardBlockHeight());

    CBitcoinAddress address(GetFoundersRewardAddressAtHeight(nHeight).c_str());
    assert(address.IsValid());
    assert(address.IsScript());
    CScriptID scriptID = get<CScriptID>(address.Get()); // Get() returns a boost variant
    CScript script = CScript() << OP_HASH160 << ToByteVector(scriptID) << OP_EQUAL;
    return script;
}
```

/src/main.cpp
```
// Coinbase transaction must include an output sending 20% of
    // the block reward to a founders reward script, until the last founders
    // reward block is reached, with exception of the genesis block.
    // The last founders reward block is defined as the block just before the
    // first subsidy halving block, which occurs at halving_interval + slow_start_shift
    if ((nHeight > 0) && (nHeight <= consensusParams.GetLastFoundersRewardBlockHeight())) {
        bool found = false;

        BOOST_FOREACH(const CTxOut& output, block.vtx[0].vout) {
            if (output.scriptPubKey == Params().GetFoundersRewardScriptAtHeight(nHeight)) {
                if (output.nValue == (GetBlockSubsidy(nHeight, consensusParams) / 5)) {
                    found = true;
                    break;
                }
            }
        }

        if (!found) {
            return state.DoS(100, error("%s: founders reward missing", __func__), REJECT_INVALID, "cb-no-founders-reward");
        }
    }
```

**Comment by joshuayabut** [comment]
The solution is ready for testing:

https://github.com/joshuayabut/z-nomp/commit/ce38771fedefecb5152d8aa84590b9e54633c43f
https://github.com/joshuayabut/node-stratum-pool/commit/1e83fc5ef4e3c9dbae6f4f460500a3e133a01d4f

**Comment by megacrypto** [comment]
i was about to re-install z-nomp and i'm targeting zcash ... so to test i just follow the normal steps? or should do something for the above 2 mentioned files? (apologies for the noob question ... fairly new to using git updates / merges / and all of it)

**Comment by joshuayabut** [comment]
Hello, I've just merged it into master so you'll just need to run:

```
git pull
npm update
npm install
```
then you can run Z-NOMP as normal with npm start.

**Comment by coolsd** [comment]
are inserted
2016-12-21 11:54:51 [Pool]      [zcash] (Thread 1) getblocktemplate call failed for daemon instance 0 with error {"type":"request error","message":"read ECONNRESET"}
2016-12-21 11:54:52 [Pool]      [zcash] (Thread 5) getblocktemplate call failed for daemon instance 0 with error {"type":"request error","message":"read ECONNRESET"}
2016-12-21 11:54:52 [Pool]      [zcash] (Thread 4) Share accepted at diff 5/5.67942917 by coolsd.1 [::ffff:192.168.10.112]
2016-12-21 11:54:52 [MySQL]     [zcash] Share inserted
2016-12-21 11:54:52 [Pool]      [zcash] (Thread 5) getblocktemplate call failed for daemon instance 0 with error {"type":"request error","message":"read ECONNRESET"}
2016-12-21 11:54:53 [Pool]      [zcash] (Thread 4) Share accepted at diff 5/6.73969007 by coolsd.1 [::ffff:192.168.10.112]
2016-12-21 11:54:53 [MySQL]     [zcash] Share inserted
2016-12-21 11:54:53 [Pool]      [zcash] (Thread 1) getblocktemplate call failed for daemon instance 0 with error {"type":"request error","message":"read ECONNRESET"}
2016-12-21 11:54:53 [Pool]      [zcash] (Thread 2) getblocktemplate call failed for daemon instance 0 with error {"type":"request error","message":"read ECONNRESET"}
2016-12-21 11:54:53 [Pool]      [zcash] (Thread 7) getblocktemplate call failed for daemon instance 0 with error {"type":"request error","message":"read ECONNRESET"}
2016-12-21 11:54:53 [Pool]      [zcash] (Thread 8) getblocktemplate call failed for daemon instance 0 with error {"type":"request error","message":"read ECONNRESET"}
2016-12-21 11:54:53 [Pool]      [zcash] (Thread 7) getblocktemplate call failed for daemon instance 0 with error {"type":"request error","message":"read ECONNRESET"}
2016-12-21 11:54:53 [Pool]      [zcash] (Thread 5) getblocktemplate call failed for daemon instance 0 with error {"type":"request error","message":"read ECONNRESET"}

**Comment by coolsd** [comment]
2016-12-21 11:55:16 [Master]    [PoolSpawner] Fork 6 died, spawning replacement worker...
/root/nomp4/node_modules/stratum-pool/lib/pool.js:577
                        result.response.miner = subsidy.miner;
                                                       ^

TypeError: Cannot read property 'miner' of undefined
    at /root/nomp4/node_modules/stratum-pool/lib/pool.js:577:56
    at itemFinished (/root/nomp4/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /root/nomp4/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/root/nomp4/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/nomp4/node_modules/stratum-pool/lib/daemon.js:95:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by coolsd** [comment]
zcash.json

{
    "enabled": true,
    "coin": "zcash.json",

    "address": "t1NB1GVXeHVHZzKgCx6oDhFBLPi6X4KWAxE",
    "_comment_address": "a transparent address to send coinbase rewards to and to transfer to zAddress.",

    "zAddress": "zcZGfifF1j7ankQVJh6z3oNEgdZBZuembTbE3t6N1PZzed9yL1tt2q49hx5FX6c5NRBbvKYagkb3kCvAkUgvGapMBG9XLYn",
    "_comment_zAddress": "a private address used to send coins to tAddress.",

    "tAddress": "t1WmGj3XCJPoiqgaFPQyB6dMejMJYHtpoz5",
    "_comment_tAddress": "transparent address used to send payments",

    "walletInterval": 10,

    "rewardRecipients": {
    },

    "paymentProcessing": {
        "enabled": false,
        "paymentInterval": 20,
        "minimumPayment": 70,
        "daemon": {
            "host": "192.168.10.32",
            "port": 8234,
            "user": "usr",
            "password": "xxxxxxxxxxxxxxx"
        }
    },

    "ports": {
        "13034": {
            "diff": 0.5,
            "varDiff": {
                "minDiff": 0.5,
                "maxDiff": 16,
                "targetTime": 15,
                "retargetTime": 90,
                "variancePercent": 30
            }
        },
        "13035": {
            "diff": 5,
            "varDiff": {
                "minDiff": 5,
                "maxDiff": 16,
                "targetTime": 15,
                "retargetTime": 90,
                "variancePercent": 30
            }
        }
    },


    "daemons": [
        {
            "host": "192.168.10.32",
            "port": 8234,
            "user": "usr",
            "password": "xxxxxxxxxxxxxxxxxxx"
        }
    ],

    "p2p": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 19333,
        "disableTransactions": true
    },

    "mposMode": {
        "enabled": true,
        "host": "192.168.10.42",
        "port": 3306,
        "user": "root",
        "password": "xxxxx",
        "database": "zec",
        "checkPassword": false,
        "autoCreateWorker": true
    }

}

**Comment by joshuayabut** [comment]
What this is saying is that it can't read the getblocktemplate and getblocksubsidy result from the zcash daemon. Are you sure the password is correct and you have the right permissions?
```
2016-12-21 11:54:51 [Pool] [zcash] (Thread 1) getblocktemplate call failed for daemon instance 0 with error {"type":"request error","message":"read ECONNRESET"}
2016-12-21 11:54:52 [Pool] [zcash] (Thread 5) getblocktemplate call failed for daemon instance 0 with error {"type":"request error","message":"read ECONNRESET"}
2016-12-21 11:54:52 [Pool] [zcash] (Thread 4) Share accepted at diff 5/5.67942917 by coolsd.1 [::ffff:192.168.10.112]
```
```
2016-12-21 11:55:16 [Master] [PoolSpawner] Fork 6 died, spawning replacement worker...
/root/nomp4/node_modules/stratum-pool/lib/pool.js:577
result.response.miner = subsidy.miner;
```

**Comment by coolsd** [comment]
[
![1](https://cloud.githubusercontent.com/assets/7413058/21378298/5e8872a8-c780-11e6-97ee-cb48204cc1f7.png)
![2](https://cloud.githubusercontent.com/assets/7413058/21378297/5e86f3ec-c780-11e6-97c1-60a1c30d5fde.png)
![3](https://cloud.githubusercontent.com/assets/7413058/21378299/5e892932-c780-11e6-90ab-de9bebf5fd74.png)


](url)

**Comment by coolsd** [comment]
root@ubuntu:~/nomp4# npm start

> z-nomp@0.0.4 start /root/nomp4
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js

^C
root@ubuntu:~/nomp4# 2016-12-21 17:04:16 [POSIX]        [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2016-12-21 17:04:16 [Master]    [CLI] CLI listening on port 17118
^C
root@ubuntu:~/nomp4# npm start

> z-nomp@0.0.4 start /root/nomp4
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js

2016-12-21 17:04:21 [POSIX]     [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2016-12-21 17:04:21 [Master]    [CLI] CLI listening on port 17118
2016-12-21 17:04:22 [Switching] [Setup] (Thread 1) Loading last proxy state from redis
/root/nomp4/node_modules/bs58check/index.js:46
  if (!payload) throw new Error('Invalid checksum')
                ^

Error: Invalid checksum
    at Object.decode (/root/nomp4/node_modules/bs58check/index.js:46:23)
    at Object.fromBase58Check (/root/nomp4/node_modules/bitcoinjs-lib-zcash/src/address.js:8:27)
    at Object.exports.createGeneration (/root/nomp4/node_modules/stratum-pool/lib/transactions.js:83:46)
    at new BlockTemplate (/root/nomp4/node_modules/stratum-pool/lib/blockTemplate.js:35:35)
    at JobManager.processTemplate (/root/nomp4/node_modules/stratum-pool/lib/jobManager.js:123:32)
    at /root/nomp4/node_modules/stratum-pool/lib/pool.js:579:66
    at itemFinished (/root/nomp4/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /root/nomp4/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/root/nomp4/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/nomp4/node_modules/stratum-pool/lib/daemon.js:95:17)
2016-12-21 17:04:22 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...
2016-12-21 17:04:22 [Switching] [Setup] (Thread 2) Loading last proxy state from redis
/root/nomp4/node_modules/bs58check/index.js:46
  if (!payload) throw new Error('Invalid checksum')
                ^

Error: Invalid checksum
    at Object.decode (/root/nomp4/node_modules/bs58check/index.js:46:23)
    at Object.fromBase58Check (/root/nomp4/node_modules/bitcoinjs-lib-zcash/src/address.js:8:27)
    at Object.exports.createGeneration (/root/nomp4/node_modules/stratum-pool/lib/transactions.js:83:46)
    at new BlockTemplate (/root/nomp4/node_modules/stratum-pool/lib/blockTemplate.js:35:35)
    at JobManager.processTemplate (/root/nomp4/node_modules/stratum-pool/lib/jobManager.js:123:32)
    at /root/nomp4/node_modules/stratum-pool/lib/pool.js:579:66
    at itemFinished (/root/nomp4/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /root/nomp4/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/root/nomp4/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/nomp4/node_modules/stratum-pool/lib/daemon.js:95:17)
2016-12-21 17:04:22 [Master]    [PoolSpawner] Fork 1 died, spawning replacement worker...
