### ISSUE TITLE
Payment processor crashes

### ISSUE THREAD

**Issue by aayanl** [joshuayabut/z-nomp#4]
```2016-11-20 12:19:24 [Payments]	[zclassic] Error detecting number of satoshis in a coin, cannot do payment processing. Tried parsing: {"result":12.50000000,"error":null,"id":1479662364061}

/home/aayanl/z-nomp/node_modules/async/dist/async.js:985
        if (fn === null) throw new Error("Callback was already called.");
                               ^
Error: Callback was already called.
    at /home/aayanl/z-nomp/node_modules/async/dist/async.js:985:32
    at /home/aayanl/z-nomp/node_modules/async/dist/async.js:3850:13
    at apply (/home/aayanl/z-nomp/node_modules/async/dist/async.js:41:25)
    at /home/aayanl/z-nomp/node_modules/async/dist/async.js:76:12
    at /home/aayanl/z-nomp/libs/paymentProcessor.js:98:21
    at itemFinished (/home/aayanl/z-nomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /home/aayanl/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/home/aayanl/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/aayanl/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at IncomingMessage.emit (events.js:129:20)
2016-11-20 12:19:24 [Master]	[Payment Processor] Payment processor died, spawning replacement...
```

Payment Processing in zclassic.json 
```
"paymentProcessing": {
        "enabled": true,
        "paymentInterval": 20,
        "minimumPayment": 0.2,
        "daemon": {
            "host": "127.0.0.1",
            "port": 8000,
            "user": "aayan",
            "password": "hardrat"
        }
    }

```

**Comment by aayanl** [comment]
https://github.com/zone117x/node-open-mining-portal/issues/470 Doing that did the trick, should Z-Nomp also use those dependency versions?

**Comment by joshuayabut** [comment]
Ah looks like I need to refactor that code. Compatibility with 0.10x broke with the use of bitcoinjs-lib and nan due to some API changes. I'll have a deeper look when I get home tonight.

**Comment by joshuayabut** [comment]
I've rewritten some code and it's working locally. I'll push to master in a day or two when I finish testing.

**Comment by aayanl** [comment]
I have a block explorer for testnet running if you need to verify if things are going through http://73.152.244.148/testnet/index.php

**Comment by joshuayabut** [comment]
See #5

**Comment by sonicdx10** [comment]
Hey there, I have a doubt with the payment process since, when using a version of the payments process I can do them but zec does not work, however the 3 others yes (zdash, zclassic, komodo), when changing the "file "To another version, the 4 pool starts but there is no such payment process.  server mexpool.ddns.net:8080

**Comment by sonicdx10** [comment]
/home/dimi/z-nomp/libs/paymentProcessor.js:172
                for (var i = 0, len = result[0].response.length; i < len; i++) {
                                                        ^

TypeError: Cannot read property 'length' of null
    at /home/dimi/z-nomp/libs/paymentProcessor.js:172:57
    at /home/dimi/z-nomp/node_modules/stratum-pool/lib/daemon.js:175:17
    at /home/dimi/z-nomp/node_modules/async/dist/async.js:359:16
    at iteratorCallback (/home/dimi/z-nomp/node_modules/async/dist/async.js:935:13)
    at /home/dimi/z-nomp/node_modules/async/dist/async.js:843:16
    at itemFinished (/home/dimi/z-nomp/node_modules/stratum-pool/lib/daemon.js:157:17)
    at /home/dimi/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/home/dimi/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/dimi/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at emitNone (events.js:91:20)
2017-03-07 08:05:48 [Master]    [Payment Processor] Payment processor died, spawning replacement...
