### ISSUE TITLE
Stratum daemon dies in subsidy.miner

### ISSUE THREAD

**Issue by ddobreff** [joshuayabut/z-nomp#43]
/home/zcash/Pool/portal-znomp/node_modules/stratum-pool/lib/pool.js:577
                        result.response.miner = subsidy.miner;
                                                       ^

TypeError: Cannot read property 'miner' of undefined
    at /home/zcash/Pool/portal-znomp/node_modules/stratum-pool/lib/pool.js:577:56
    at itemFinished (/home/zcash/Pool/portal-znomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /home/zcash/Pool/portal-znomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/home/zcash/Pool/portal-znomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/zcash/Pool/portal-znomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
2016-12-21 17:41:18 [Master]        [PoolSpawner] Fork 0 died, spawning replacement worker...

**Comment by joshuayabut** [comment]
Hello this error means that the pool isn't able to parse the response to the getblocksubsidy rpc command. Can you double check that your rpc connection details are correct and that the wallet is sync'd?

**Comment by coolsd** [comment]
I also encountered the same problem, will run after a period of time. There's no problem in the wallet.

**Comment by ddobreff** [comment]
Hi, after a serious amount of testing I found out that global port 8233 is blocked by my ISP. Rerouted through VPN and for now there is no error.

**Comment by joshuayabut** [comment]
Glad to hear it's fixed!
