### ISSUE TITLE
what's this errer

### ISSUE THREAD

**Issue by ceozero** [joshuayabut/z-nomp#46]
/home/z-nomp/node_modules/stratum-pool/lib/pool.js:619
        if (typeof(_this.jobManager.currentJob) !== 'undefined' && blockHash !== _this.jobManager.currentJob.rpcData.previousblockhash) {
                                   ^

TypeError: Cannot read property 'currentJob' of undefined
    at pool.processBlockNotify (/home/z-nomp/node_modules/stratum-pool/lib/pool.js:619:36)
    at process.<anonymous> (/home/z-nomp/libs/poolWorker.js:42:39)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at processEmit [as emit] (/home/z-nomp/node_modules/signal-exit/index.js:155:32)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by joshuayabut** [comment]
It's saying that the pool can't read the response for getblocktemplate from the wallet. It could be that the wallet hasn't fully synced yet and will go away by itself or that the configuration settings aren't right.

**Comment by ceozero** [comment]
@joshuayabut  Is this working properly? Why can not find the block for a long time.



2016-12-22 19:33:01 [Switching] [Setup] (equihash) Setting proxy difficulties after pool start
2016-12-22 19:33:01 [Website]   [zclassic] Unauthorized RPC access - invalid RPC username or password
2016-12-22 19:33:01 [Switching] [Setup] (Thread 2) Loading last proxy state from redis
2016-12-22 19:33:01 [Pool]      [zclassic] (Thread 2) Share processing setup with redis (127.0.0.1:6379)
2016-12-22 19:33:01 [Pool]      [zclassic] (Thread 2) Stratum Pool Server Started for zclassic [ZCL] {equihash}
2016-12-22 19:33:01 [Switching] [Setup] (equihash) Setting proxy difficulties after pool start
2016-12-22 19:33:01 [Master]    [PoolSpawner] Spawned 1 pool(s) on 4 thread(s)
2016-12-22 19:33:01 [Switching] [Setup] (Thread 3) Loading last proxy state from redis
2016-12-22 19:33:01 [Pool]      [zclassic] (Thread 3) Share processing setup with redis (127.0.0.1:6379)
2016-12-22 19:33:01 [Pool]      [zclassic] (Thread 3) Stratum Pool Server Started for zclassic [ZCL] {equihash}
2016-12-22 19:33:01 [Switching] [Setup] (equihash) Setting proxy difficulties after pool start
2016-12-22 19:33:01 [Switching] [Setup] (Thread 4) Loading last proxy state from redis
2016-12-22 19:33:01 [Pool]      [zclassic] (Thread 4) Share processing setup with redis (127.0.0.1:6379)
2016-12-22 19:33:01 [Pool]      [zclassic] (Thread 4) Stratum Pool Server Started for zclassic [ZCL] {equihash}
2016-12-22 19:33:01 [Switching] [Setup] (equihash) Setting proxy difficulties after pool start
2016-12-22 19:33:17 [Pool]      [zclassic] (Thread 4) Block notification via RPC polling
2016-12-22 19:33:17 [Pool]      [zclassic] (Thread 1) Block notification via RPC polling
2016-12-22 19:33:17 [Pool]      [zclassic] (Thread 2) Block notification via RPC polling
2016-12-22 19:33:18 [Pool]      [zclassic] (Thread 3) Block notification via RPC polling
Pool workers notified
2016-12-22 19:34:12 [Pool]      [zclassic] (Thread 4) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2016-12-22 19:34:12 [Pool]      [zclassic] (Thread 2) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2016-12-22 19:34:12 [Pool]      [zclassic] (Thread 1) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2016-12-22 19:34:13 [Pool]      [zclassic] (Thread 3) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2016-12-22 19:35:07 [Pool]      [zclassic] (Thread 4) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2016-12-22 19:35:07 [Pool]      [zclassic] (Thread 2) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2016-12-22 19:35:07 [Pool]      [zclassic] (Thread 1) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2016-12-22 19:35:08 [Pool]      [zclassic] (Thread 3) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2016-12-22 19:35:52 [Pool]      [zclassic] (Thread 3) Block notification via RPC polling
2016-12-22 19:35:52 [Pool]      [zclassic] (Thread 2) Block notification via RPC polling
2016-12-22 19:35:52 [Pool]      [zclassic] (Thread 4) Block notification via RPC polling
2016-12-22 19:35:52 [Pool]      [zclassic] (Thread 1) Block notification via RPC polling
Pool workers notified
2016-12-22 19:36:47 [Pool]      [zclassic] (Thread 3) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2016-12-22 19:36:47 [Pool]      [zclassic] (Thread 2) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2016-12-22 19:36:47 [Pool]      [zclassic] (Thread 4) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2016-12-22 19:36:47 [Pool]      [zclassic] (Thread 1) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2016-12-22 19:37:42 [Pool]      [zclassic] (Thread 3) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2016-12-22 19:37:42 [Pool]      [zclassic] (Thread 2) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2016-12-22 19:37:42 [Pool]      [zclassic] (Thread 4) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2016-12-22 19:37:42 [Pool]      [zclassic] (Thread 1) No new blocks for 55 seconds - updating transactions & rebroadcasting work

**Comment by joshuayabut** [comment]
Hi this looks pretty normal. It is checking if a block has been found every 55 seconds and if not it updates the transactions in order to include more miner fees/rewards. 

The error is showing multiple times because the pool is running in more than one thread. But if you check the timestamps it's showing expected activity.

**Comment by ceozero** [comment]
Yesterday such a situation 24 hours did not find a block, the same force SOLO day can find the block of 50. This is why?

**Comment by joshuayabut** [comment]
I can't really answer that question without knowing your total hashrate and how long you've been testing... It could just be bad luck. 

If you think something is broken you can always try the pool on testnet.
