### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by sennevb** [joshuayabut/z-nomp#49]
getting these error lately on startup:
/root/z-nomp/node_modules/stratum-pool/lib/pool.js:619
        if (typeof(_this.jobManager.currentJob) !== 'undefined' && blockHash !== _this.jobManager.currentJob.rpcData.previousblockhash) {
                                   ^

TypeError: Cannot read property 'currentJob' of undefined
    at pool.processBlockNotify (/root/z-nomp/node_modules/stratum-pool/lib/pool.js:619:36)
    at process.<anonymous> (/root/z-nomp/libs/poolWorker.js:42:39)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at processEmit [as emit] (/root/z-nomp/node_modules/signal-exit/index.js:155:32)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

any help?

**Comment by joshuayabut** [comment]
Does that error go away? I have a hunch that joinsplit generations are delaying RPC responses and causing these errors.

A work around is to lengthen the time walletInteval time in your pool config file. I'll have a more thorough look into this tommorow. And if it's a joinsplit issue then I'll submit an issue upstream into Zcash.

**Comment by sennevb** [comment]
just on lanch of npm start, not getting it after..

**Comment by joshuayabut** [comment]
Ok.. I've added another typeof check to make sure that _this.jobManager is initialized. 

You can update node-stratum-pool with:
``` bash
npm update
npm install
npm start
```

Commit: https://github.com/joshuayabut/node-stratum-pool/commit/32a305cc56fb93568f0ce578ada4709ec0cb69da
