### ISSUE TITLE
An occasional mistake

### ISSUE THREAD

**Issue by ceozero** [joshuayabut/z-nomp#57]
/root/z-nomp/node_modules/stratum-pool/lib/pool.js:576
                        result.response.miner = subsidy.miner;
                                                       ^

TypeError: Cannot read property 'miner' of undefined
    at /root/z-nomp/node_modules/stratum-pool/lib/pool.js:576:56
    at itemFinished (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /root/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
/root/z-nomp/node_modules/stratum-pool/lib/pool.js:576
                        result.response.miner = subsidy.miner;
                                                       ^

TypeError: Cannot read property 'miner' of undefined
    at /root/z-nomp/node_modules/stratum-pool/lib/pool.js:576:56
    at itemFinished (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /root/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
/root/z-nomp/node_modules/stratum-pool/lib/pool.js:576
                        result.response.miner = subsidy.miner;
                                                       ^

TypeError: Cannot read property 'miner' of undefined
    at /root/z-nomp/node_modules/stratum-pool/lib/pool.js:576:56
    at itemFinished (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /root/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
2016-12-30 18:20:07 [Master]    [PoolSpawner] Fork 1 died, spawning replacement worker...
2016-12-30 18:20:07 [Master]    [PoolSpawner] Fork 3 died, spawning replacement worker...
2016-12-30 18:20:07 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...
/root/z-nomp/node_modules/stratum-pool/lib/pool.js:576
                        result.response.miner = subsidy.miner;
                                                       ^

TypeError: Cannot read property 'miner' of undefined
    at /root/z-nomp/node_modules/stratum-pool/lib/pool.js:576:56
    at itemFinished (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /root/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
2016-12-30 18:20:07 [Master]    [PoolSpawner] Fork 2 died, spawning replacement worker...

**Comment by ceozero** [comment]
About an hour

**Comment by joshuayabut** [comment]
Can you be sure you are running the latest z-nomp version?

```bash
git pull
npm update
npm install
npm start
```

**Comment by ceozero** [comment]
yes  I update today

**Comment by aayanl** [comment]
I get this error when I tried to run the zclassic daemon on the linux subsystem for windows, if you are using the linux subsystem, z-nomp runs best on linux
