### ISSUE TITLE
Invalid checksum

### ISSUE THREAD

**Issue by VoTomas** [joshuayabut/z-nomp#59]
Hi, I'm trying to setup  z-nomp with zcash. 

I'm getting this error when starting a freshly cloned and installed z-nomp

```
/root/z-nomp/node_modules/bs58check/index.js:48
  if (!payload) throw new Error('Invalid checksum')
                ^

Error: Invalid checksum
    at Object.decode (/root/z-nomp/node_modules/bs58check/index.js:48:23)
    at Object.fromBase58Check (/root/z-nomp/node_modules/bitcoinjs-lib-zcash/src/address.js:8:27)
    at Object.exports.createGeneration (/root/z-nomp/node_modules/stratum-pool/lib/transactions.js:83:46)
    at new BlockTemplate (/root/z-nomp/node_modules/stratum-pool/lib/blockTemplate.js:35:35)
    at JobManager.processTemplate (/root/z-nomp/node_modules/stratum-pool/lib/jobManager.js:123:32)
    at /root/z-nomp/node_modules/stratum-pool/lib/pool.js:578:66
    at itemFinished (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /root/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17
```
Debian 8
Zcash version v1.0.4
nodejs version v7.3.0
redis 2.8.17

Any help would be greatly appreciated!

**Comment by joshuayabut** [comment]
It seems like your tAddress might be incorrect in the pools/zcash.conf file. Can you post that (removing any sensitive info)? Thanks!

**Comment by VoTomas** [comment]
Sure thing! Here it is: 

```
{
    "enabled": true,
    "coin": "zcash.json",

    "address": "t1VnCgWBBnF4yogkzJE8MNWunRzQ3coWV4b",
    "_comment_address": "a transparent address to send coinbase rewards to and to transfer to zAddress.",

    "zAddress": "zcGYQtte47b3qxjG2H3ZRhmPteqVT1Zehp5ocJrQuLFYVzhusWSeZANs9YemGGoFGVNVcBWiTTo4sjVWeXmPYKXyRYmMAMP",
    "_comment_zAddress": "a private address used to send coins to tAddress.",

    "tAddress": "t1MJkvFwd6TEjydzQ4YnYU9PJbWp2QoTieL",
    "_comment_tAddress": "transparent address used to send payments, make this a different address, otherwise payments will not send",

    "walletInterval": 10,

    "rewardRecipients": {
        "": 0.2,
        "": 0.3
    },

    "paymentProcessing": {
        "enabled": true,
        "paymentInterval": 20,
        "minimumPayment": 0.1,
        "daemon": {
            "host": "127.0.0.1",
            "port": 19332,
            "user": "user",
            "password": "password"
        }
    },

    "ports": {
        "3032": {
            "diff": 0.05,
            "varDiff": {
                "minDiff": 0.04,
                "maxDiff": 16,
                "targetTime": 15,
                "retargetTime": 60,
                "variancePercent": 30
            }
        }
    },

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 8232,
            "user": "user",
            "password": "password"
        }
    ],

    "p2p": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 19333,
        "disableTransactions": true
    },

    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "me",
        "password": "mypass",
        "database": "zec",
        "checkPassword": true,
        "autoCreateWorker": false
    }

}
```

**Comment by aayanl** [comment]
remove the empty rewardRecipients

**Comment by VoTomas** [comment]
Oh man, noob... Thank you for your time. :)
