### ISSUE TITLE
Error: /root/z-nomp/node_modules/bs58check/index.js:48   if (!payload) throw new Error('Invalid checksum')

### ISSUE THREAD

**Issue by a1binos** [joshuayabut/z-nomp#61]
2017-01-09 12:47:54 [Master]    [PoolSpawner] Fork 2 died, spawning replacement worker...
2017-01-09 12:47:55 [Switching] [Setup] (Thread 4) Loading last proxy state from redis
2017-01-09 12:47:55 [Pool]      [zcash] (Thread 4) Share processing setup with redis (127.0.0.1:6379)
/root/z-nomp/node_modules/bs58check/index.js:48
  if (!payload) throw new Error('Invalid checksum')
                ^

Error: Invalid checksum
    at Object.decode (/root/z-nomp/node_modules/bs58check/index.js:48:23)
    at Object.fromBase58Check (/root/z-nomp/node_modules/bitcoinjs-lib-zcash/src/address.js:8:27)
    at Object.exports.createGeneration (/root/z-nomp/node_modules/stratum-pool/lib/transactions.js:83:46)
    at new BlockTemplate (/root/z-nomp/node_modules/stratum-pool/lib/blockTemplate.js:35:35)
    at JobManager.processTemplate (/root/z-nomp/node_modules/stratum-pool/lib/jobManager.js:123:32)
    at /root/z-nomp/node_modules/stratum-pool/lib/pool.js:578:66
    at itemFinished (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /root/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
2017-01-09 12:47:55 [Master]    [PoolSpawner] Fork 3 died, spawning replacement worker...
2017-01-09 12:47:55 [Switching] [Setup] (Thread 5) Loading last proxy state from redis
2017-01-09 12:47:55 [Pool]      [zcash] (Thread 5) Share processing setup with redis (127.0.0.1:6379)
/root/z-nomp/node_modules/bs58check/index.js:48
  if (!payload) throw new Error('Invalid checksum')
                ^

Error: Invalid checksum
    at Object.decode (/root/z-nomp/node_modules/bs58check/index.js:48:23)
    at Object.fromBase58Check (/root/z-nomp/node_modules/bitcoinjs-lib-zcash/src/address.js:8:27)
    at Object.exports.createGeneration (/root/z-nomp/node_modules/stratum-pool/lib/transactions.js:83:46)
    at new BlockTemplate (/root/z-nomp/node_modules/stratum-pool/lib/blockTemplate.js:35:35)
    at JobManager.processTemplate (/root/z-nomp/node_modules/stratum-pool/lib/jobManager.js:123:32)
    at /root/z-nomp/node_modules/stratum-pool/lib/pool.js:578:66
    at itemFinished (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /root/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
2017-01-09 12:47:55 [Master]    [PoolSpawner] Fork 4 died, spawning replacement worker...
2017-01-09 12:47:55 [Switching] [Setup] (Thread 6) Loading last proxy state from redis
2017-01-09 12:47:55 [Pool]      [zcash] (Thread 6) Share processing setup with redis (127.0.0.1:6379)
/root/z-nomp/node_modules/bs58check/index.js:48
  if (!payload) throw new Error('Invalid checksum')
                ^

Error: Invalid checksum
    at Object.decode (/root/z-nomp/node_modules/bs58check/index.js:48:23)
    at Object.fromBase58Check (/root/z-nomp/node_modules/bitcoinjs-lib-zcash/src/address.js:8:27)
    at Object.exports.createGeneration (/root/z-nomp/node_modules/stratum-pool/lib/transactions.js:83:46)
    at new BlockTemplate (/root/z-nomp/node_modules/stratum-pool/lib/blockTemplate.js:35:35)
    at JobManager.processTemplate (/root/z-nomp/node_modules/stratum-pool/lib/jobManager.js:123:32)
    at /root/z-nomp/node_modules/stratum-pool/lib/pool.js:578:66
    at itemFinished (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /root/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
2017-01-09 12:47:55 [Master]    [PoolSpawner] Fork 5 died, spawning replacement worker...

**Comment by aayanl** [comment]
can you post your pool config?

**Comment by a1binos** [comment]
remove the empty reward recipients 
Thanks.
