### ISSUE TITLE
Error binding to 8080

### ISSUE THREAD

**Issue by megacrypto** [joshuayabut/z-nomp#68]
getting this error:

> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: bind EADDRINUSE 0.0.0.0:8080
>     at Object.exports._errnoException (util.js:1022:11)
>     at exports._exceptionWithHostPort (util.js:1045:20)
>     at cb (net.js:1327:16)
>     at rr (cluster.js:627:14)
>     at Worker.<anonymous> (cluster.js:596:9)
>     at process.<anonymous> (cluster.js:768:8)
>     at emitTwo (events.js:111:20)
>     at process.emit (events.js:191:7)
>     at processEmit [as emit] (/home/mylin/Pools/ZNOMP/znomp/node_modules/signal-exit/index.js:155:32)
>     at process.nextTick (internal/child_process.js:752:12)
> 2017-01-19 14:36:40 [Master]    [Website] Website process died, spawning replacement...

**Comment by megacrypto** [comment]
seems that i have something running on port 8080 ... changed port in config.json and all worked fine
