### ISSUE TITLE
run manner comes this error

### ISSUE THREAD

**Issue by innova-market** [joshuayabut/z-nomp#9]
When you run manner comes this error

```
2016-11-28 01:16:40 [Switching] [Setup] (equihash) Setting proxy difficulties after pool start
/home/evanto/z-nomp/node_modules/stratum-pool/lib/stratum.js:282
            zeroPad = zeroPad.repeat(64 - adjPow.toString(16).length);
                              ^
TypeError: undefined is not a function
    at sendDifficulty (/home/evanto/z-nomp/node_modules/stratum-pool/lib/stratum.js:282:31)
    at null.<anonymous> (/home/evanto/z-nomp/node_modules/stratum-pool/lib/pool.js:485:26)
    at emit (events.js:110:17)
    at handleSubscribe (/home/evanto/z-nomp/node_modules/stratum-pool/lib/stratum.js:96:15)
    at handleMessage (/home/evanto/z-nomp/node_modules/stratum-pool/lib/stratum.js:62:17)
    at /home/evanto/z-nomp/node_modules/stratum-pool/lib/stratum.js:237:25
    at Array.forEach (native)
    at Socket.<anonymous> (/home/evanto/z-nomp/node_modules/stratum-pool/lib/stratum.js:223:26)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
2016-11-28 01:16:43 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...
2016-11-28 01:16:43 [Switching] [Setup] (Thread 2) Loading last proxy state from redis
2016-11-28 01:16:43 [Pool]      [zclassic] (Thread 2) Share processing setup with redis (127.0.0.1:6379)
2016-11-28 01:16:43 [Pool]      [zclassic] (Thread 2) No rewardRecipients have been setup which means no fees will be taken
2016-11-28 01:16:43 [Pool]      [zclassic] (Thread 2) Stratum Pool Server Started for zclassic [ZCL] {equihash}
2016-11-28 01:16:43 [Switching] [Setup] (equihash) Setting proxy difficulties after pool start

```

**Comment by aayanl** [comment]
I can confirm that im having the same issue

**Comment by joshuayabut** [comment]
This error comes from an older version of Node not having the 'repeat' method. Try running 'sudo n stable'. And if you don't have n already installed do 'sudo npm install n -g' before it.

**Comment by aayanl** [comment]
Yeah that fixed it

**Comment by joshuayabut** [comment]
Sweet! Closing this out.
